### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by ChitraSatish** [PARINetwork/pari#10]
1. Click on the more link in the Show case
2. You get to see the Debating rice in the forest of learning.
3. In the bottom of the page - we see "You may also like"
4. When clicking on any of these links - we get a few links.
The following links are broken and we get "The page you requested does not exist"
a) Niyamgiri - The mountain that gives
b) Sikkimese Smile

In the same page click the here link from "Full transcript of GM debate here)
At the bottom pane we have a few links. The following links are broken.
c) Oliver Twist seeks food security
d) Food Security - by definition
e) Reaping gold through cotton and news print
f) Of Loan waivers and tax waivers

I realized that the you may like panel is populated with links selected at random. The following also do not work:
g) Saving women seeds
h) Polepally protesters sway poll outcome
i) No deception to mislead farmers on seeds
j) Andhra farmers lose crores in Insurance
k) Giving voice to the voiceless

I am not sure whether all the four links fail in the GM debate's transcript page. Please check. A lot of broken links. Needs to be taken care of

In the same way I clicked on the more link from the Watch. It took me to the baked earth. In that in the bottom panel the following links were broken:
l) Clouds of despair - The poor and the permanent 'drought'
m) Games big corporations play

**Comment by theju** [comment]
The articles that were not found were draft articles. Should be fixed now. Please verify.

**Comment by theju** [comment]
I think this also has been fixed as I have not seen a draft article appear. Please reopen if not fixed.
