### ISSUE TITLE
Transcript link is not available or not opening when the language is selected as Tamil or Hindi

### ISSUE THREAD

**Issue by ChitraSatish** [PARINetwork/pari#11]
1. Click on the more link of the Showcase from the home page.
2. We are taken to the Debating rice in the forest of learning page.
3. Choose tamil from the pick list "Choose language"
4. The whole page is now rendered in Tamil. In this page we see the text to go and see the transcript of the debate. But there is no hyperlink.
5. I change the language to Hindi. Here we get to see the link to go to the transcript. The link is pointing to new.ruralindiaonline.org. So we get a message "Cannot verify Server Identity" (Tested in safari browser from an iPad)

**Comment by theju** [comment]
Should be fixed now. Any reference to new.ruralindia... is invalid.

**Comment by theju** [comment]
Fixed. Please reopen if not fixed.
