### ISSUE TITLE
Social sharing content for articles

### ISSUE THREAD

**Issue by gayathrim** [PARINetwork/pari#110]
Estimate: M

**In Scope:**
- OGP for articles should be introduced with the below content
- Twitter card view meta tags to be introduced with the below content
- Twitter message as shown below
- FB content update like below.
- SEO meta description to be added

[Social Sharing content sheet](https://docs.google.com/spreadsheets/d/1gfatfScEloRFrrlzg4IiwXsjOwZW2oOFY3NnuTQVcS8/edit#gid=0)

**Dev tasks:**
1. Host name + Robots.txt - Robots.txt is done. Waiting for praveen on host name configuration.
2. Encoding the url -Done
3. SSL? - Yet to confirm. 
4. Extracting to template -Done

**Defects**
- There is an extra space in front of the twitter URL - Twitter API issue
- The images are getting cropped by twitter sometimes. Need to check if there is a way out of this. - parked for now

**Comment by sankarpatw** [comment]
@gayathrim 
Leading space addition to URL  tweet is the behaviour of twitter api .
