### ISSUE TITLE
Looks like the same image is used for the tiles of two articles

### ISSUE THREAD

**Issue by ChitraSatish** [PARINetwork/pari#12]
1. From the home page click on the more of the Watch
2. It takes you to the Baked Earth
3. In the bottom panel - "You may also like" link - the same image is used for the links - Clouds of despair: The poor and the permanent 'drought' & 36 tube wells and digging, a scorching message emerges from deep down. Looks like it belongs to the second article. We need to associate the correct image to the first article

**Comment by theju** [comment]
I think this also should've gotten fixed with the [0dc430cb] but let's keep it open for a little more while to be sure.

**Comment by ChitraSatish** [comment]
Hi all
I  am going on a vacation for the next four days. Will resume testing from next Tuesday.  Will not be able to attend this week's call.
Regards
Chitra Satiah

-----Original Message-----

**Comment by theju** [comment]
This would've been fixed with #10. Please reopen if not fixed.
