### ISSUE TITLE
Related stories should show related articles in default language

### ISSUE THREAD

**Issue by gayathrim** [PARINetwork/pari#147]
S
In Scope:

- Related articles should show only default language content i.e If it is a English site then should show only English content.
- Related articles relevance should be based on author, location and title.
- http://staging.ruralindiaonline.org/articles/lets-solve-the-pricing-problem-once-and-for-all/

**Defects:**
- In [this](http://staging.ruralindiaonline.org/articles/no-ticket-will-travel/) article, author first name is same but they are two different authors- Rahul M and Rahul Maganti. Related articles should fetch only from Rahul M list of article.?

**Comment by sankarpatw** [comment]
Changes can be
