### ISSUE TITLE
Ability to add a two column Block Quotes and text module

### ISSUE THREAD

**Issue by gayathrim** [PARINetwork/pari#150]
In Scope:
Estimate: XS
Backend:
- Ability to give block quotes and text to be displayed in two columns. 
- Should be able to swap text column and block quote column.
- Block quotes column can take only text with italics
- Text module should behave the same as the full width text module.

Frontend:
- Blockquotes + text should follow the same styling as in the mockup.
- Responsiveness to be handled.

Defects:
- <del> In Tablet view, there is more space between the featured image and the block quote beginning - Done
- <del> When there is a extra line character in the blockquote then two blockquote elements appear on UI. Ideally the entire content in the block quote should be inside one blockquote including extra line etc. -Done
- <del> Blockquote should start in between the first two lines of the paragraph - Done
- <del> Blockquote font size is slightly big compared to mockup - Done
- <del> Blockquote font is different from mockup - Done
- <del> When there is extra space in the para in blockquote, the adjacent para is getting appended to this blockquote para. Should start after blockquote only. - Done
- <del> In urdu, when blockquote in on right then the column spacing is too much - Done
- <del> When we do italics on urdu text then there is space before the text.
- <del> When there is a para followed by blockquote module, the top line of blockquote hits the previous paragraph - Done
- <del> When the blockquote is starting there is very less space between featured content and this block. Should be the same as paragraph module starting space from featured content- Done
- <del> Spacing between different modules should be the same as paragraph spacing.
- <del> When the article starts with blockquote module (left aligned) then the alignment of the blockquote is not right. Should be the same starting line as it is when it is in the middle.
- <del> In Urdu, when para text is short there is extra space in responsive mode.
- <del> Paras in text column does not have any space in quote module.

**Comment by sankarpatw** [comment]
1. Added paragraph with quote module with only 'Bold' and 'Italic' functionality with TinyMCE editor.  Wagtail inbuilt hallo editor cannot be configured per field but it can be done globally, hence we are moving to TinyMCE editor.

Pending
--------
Styling the editor interface is pending, this seems to take some effort.

**Comment by sankarpatw** [comment]
@gayathrim 

Some observations for Urdu lang testing.

To test Urdu language block quote. Please do a publish since language code and language bidi is getting applied only after publishing. Do not use preview mode to test.

1. Please limit the quote length for Urdu languages. 
2. Quotes more than 5 lines will distort the alignment and looks there are more space between the quote and the paragraph.
