### ISSUE TITLE
Crop and resize images uploaded to the PARI website

### ISSUE THREAD

**Issue by jemjoseph** [PARINetwork/pari#202]
As a content editor uploading an image to the Content Management System
I want to crop and resize the images I upload 
So that I can have the right sized image on the website depending on the purpose of the image

Overview:
The PARI website contains a lot of images which are for multiple purposes e.g: Cover image for articles, as part of albums and exhibitions, faces, thumbnails etc. Depending on the purpose of the image, the content editor might want to crop the image and upload only a part of it.

In Scope:
- Uploading an image to the images section of the CMS or directly to the Articles, Albums, Faces, Home Page, Gallery Home page etc
- Previewing the image uploaded to the CMS by the user
- Cropping a part of the image to be uploaded to the website
- Changing the size of the image to be uploaded to the website
- Good to have features- Ability to rotate picture, lateral inversion and vertical inversion

Acceptance Criteria:
Given that I am a content editor using the CMS system
When I upload images to the CMS
Then I should be able to preview the images that I upload

Given that I uploaded  an image to the CMS 
When I am able to preview the image
Then I should be able to crop a section of the image that I want to be loaded 

Given that I uploaded  an image to the CMS 
When I am able to preview the image
Then I should be able to change the size of the image

**Comment by gounder** [comment]
Not going to resolve
