### ISSUE TITLE
Redesign of the single resource page

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#272]
Here are some opinions from teammates

Can we place the focus on the left and the factoids on the right? 
SMJ: On the internet, people tend to read content that’s on the left first (Source: The Yahoo Style Guide). Since the focus introduces people to the report, I’d say it’s important read it before they read the factoids. 

Can we have a slot for the volunteer credit?

Can we have a different kind of display for articles in the Library? 
SMJ: They will have 50-word abstracts not the focus and factoids.

Can we have a different date format? 
SMJ: It would be good if we can put in dates in the following formats: DD/MM/YY and MM/YY. Right now, we only use this format: DD/MM/YY. Many reports only mention the month and year of publication, and do not provide the date. So it would be good if we can have flexibility. 

We need new categories for Library because Things We Make, Things We Do don’t really fit here. The names of the rooms could be those categories.

**Comment by adityadipankar** [comment]
This is done.
