### ISSUE TITLE
"PARI for students, teacher and researchers" has a broken link in it 

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#290]
"PARI has specific guidelines for videos generated" link is broken

https://ruralindiaonline.org/pages/pari-teachers-students

**Comment by raunaqgupta** [comment]
Seems like `Video Guidelines` does not have a section of it's own which even this section is trying to reference: https://ruralindiaonline.org/pages/guidelines#section-1-8

**Comment by raunaqgupta** [comment]
Okay, so the video guidelines does have a section which was not apparent since I did not realize the left navigation pane was scrollable. This is the link to the section:

https://ruralindiaonline.org/pages/guidelines#section-6-1
