### ISSUE TITLE
Odd characters in Acknowledgements page

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#291]
https://ruralindiaonline.org/pages/acknowledgements

![ackpage](https://user-images.githubusercontent.com/6252597/35258580-73204d64-0026-11e8-840a-e3c5db005d76.png)

**Comment by raunaqgupta** [comment]
This bug is only visible in:
Platform: Windows
Browser: Google Chrome

Is possibly because of the custom font, `Fira Sans`

**Comment by siddadel** [comment]
This line separator
https://unicode-table.com/en/search/?q=
