### ISSUE TITLE
RSS Feed is broken

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#296]
RSS feed available here:
https://ruralindiaonline.org/feeds/list

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fruralindiaonline.org%2Ffeeds%2Fall%3Fformat%3Drss

We need RSS feed to be functional, valid and well-formed to use webapps like Zapier and apply to be included by aggregators.

**Comment by siddadel** [comment]
http://www.feedvalidator.org/check.cgi?url=https%3a%2f%2fruralindiaonline.org%2ffeeds%2fall

**Comment by gounder** [comment]
Duplicate of #384
