### ISSUE TITLE
Italics and formatting not working on Description of each slide in Talking Albums and Album 

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#297]
If you go to Album > To an individual album > Slides, slide 1

![slide1](https://user-images.githubusercontent.com/6252597/35376505-786da292-01d1-11e8-9f84-f51172283faf.png)

Notice that the italics in "mela" does not appear in the frontend

![slide1ui](https://user-images.githubusercontent.com/6252597/35376521-86e76a60-01d1-11e8-81a8-25ad0b349106.png)

**Comment by kushboojain** [comment]
There's a specific style for it that says on italics, change the font style to normal. Done as part of 
[Issue #61](https://github.com/PARINetwork/pari/issues/61). It says remove italics for description

**Comment by siddadel** [comment]
@kushboojain We will have to overrule that and add the italics. Editorial team need italics in that description. Possible?

**Comment by kushboojain** [comment]
Yes it's possible.

**Comment by kushboojain** [comment]
I have pushed the changes to master
