### ISSUE TITLE
Resource page - Tiling alignment issue in Safari from iPad

### ISSUE THREAD

**Issue by ChitraSatish** [PARINetwork/pari#3]
1. I clicked on the more > under Rural Bytes from the home page. It takes me to the resources page. 
2. When I view the resources in an iPad using safari, I see the resources tiling has issues. It has two tiles in one row and one tile in the next row. It alternates in this fashion.
When I see in the desk top I see three tiles in a row. Can this be fixed in tabled based devices?

**Comment by theju** [comment]
Yup, this is a bug. Fixed. Please verify and close.

**Comment by ChitraSatish** [comment]
Verified and found that the Issue is fixed.

**Comment by ChitraSatish** [comment]
Issue has been  verified and closed

On Mon, Sep 28, 2015 at 7:57 PM, Thejaswi Puthraya <notifications@github.com
