### ISSUE TITLE
Implement a Newsletter for PARI

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#302]
As an admin I need a newsletter service such that I am able to send bimonthly updates to around 2000 email addresses (increasing)

As a webuser I need a newsletter such that I can subscribe to PARI's newsletter receive regular updates and bimonthly digest

As a webuser I need a differentiated dialogue so I can receive only selected types of notifications -- article, face, album, resource, translation (in one or all language(s)

As an admin I need a newsletter service such that there are certain automated notifications that go out to selected group of emails based on events such as New Article Uploaded, New Face Uploaded, New Album uploaded, New Resource, New Translation uploaded.

**Comment by nikhilsane** [comment]
Siddharth, Bimonthly means two emails per user per month? Or 1 email per user every 2 months?

**Comment by siddadel** [comment]
Yes fortnightly. Twice a month.
