### ISSUE TITLE
Embed captions for URDU should be CENTRE aligned

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#333]
Presently they are automatically right aligned

**Comment by charl3sj** [comment]
@siddadel What are embed captions?

**Comment by siddadel** [comment]
Captions for video/YouTube frame embes? Or captions for script?

**Comment by charl3sj** [comment]
@siddadel Can you point me to an example?

**Comment by siddadel** [comment]
Adding Qamar here.

Qamar bhai - Will you be able to help Charles understand our Urdu text
alignment issue?
