### ISSUE TITLE
Pari articles etc in an overlay on the India map

### ISSUE THREAD

**Issue by swapneshb** [PARINetwork/pari#350]
We can have an overlay of Pari on the map of India. It can basically show the density of articles/videos etc and then the user can zoom into an area of interest. The zoom will separate out clusters of points into individual points and provide more detail in mouse-over.

This will provide a nice summarized view as well as an easy way to navigate through the articles from a geographical point of view.

**Comment by siddadel** [comment]
Do you mean this?
https://ruralindiaonline.org/map

**Comment by swapneshb** [comment]
Yes, thanks for sharing. Wonder how I missed it. Following PARI  for quite
a while now. Also, can you add this email to the google group?

Regards,
Swapnesh
