### ISSUE TITLE
Replace IMPS with UPI

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#369]
References to IMPS can be replaced with UPI as IMPS has been mostly superseded by Unified Payment Interface (UPI).

UPI allows people to make payments not just through their bank accounts but also through wallets like Paytm, Google Pay etc and for free (with no transaction charges)!

Please check the following link on HDFC page to get your UPI Id:
https://www.hdfcbank.com/personal/making-payments/fund-transfer/upi

Replace the section on IMPS with UPI and add the UPI Id on the Donate page. You can also add a BharatQR code that people can scan and donate (check an example at [1]). The HDFC mobile app should have details on how to generate the QR code. You can have this QR code printed on the visiting cards or on a piece of paper that Sainath can take for his talks.

[1] https://www.bhimupi.org.in/donation-digitized-with-bhim-upi

**Comment by gounder** [comment]
We will not moving to UPI soon. Please mark as a not going to resolve
