### ISSUE TITLE
Language Page

### ISSUE THREAD

**Issue by charl3sj** [PARINetwork/pari#379]
Implement our Language page where fast depleting Indian tongues get a page of their own.

- [ ] Change the theme to support this feature
- [ ] Create template for language page for the content upload person to add/edit content

**Comment by siddadel** [comment]
This issue already exists: https://github.com/PARINetwork/pari/issues/338

**Comment by petmongrels** [comment]
duplicate, to be archived

**Comment by siddadel** [comment]
Thanks for this and starting the project.
