### ISSUE TITLE
PARI on a pendrive

### ISSUE THREAD

**Issue by charl3sj** [PARINetwork/pari#380]
Make it possible to download the entire PARI site on a pendrive. Make it possible to pick and choose stories/pictures/videos from PARI and create a downloadable version.

**Evaluate httrack vs wget**

- [ ] Configure tool like wget for downloading all the contents into file system (1)
- [ ] Setup a user interface to trigger this process. Setup something like React Admin to allow users to configure their choice of content to download. Create another configurable version of wget to download only selected resources. (8)
- [ ] Create custom document structure which can be used by the user to navigate the content on the pendrive/offline. (4)
- [ ] Upload the downloadable versions to a content delivery network that support large files (2)

**Comment by siddadel** [comment]
Charles - I believe you might be opening issues already present.

**Comment by siddadel** [comment]
https://github.com/PARINetwork/pari/issues/289

**Comment by petmongrels** [comment]
Closing this issue, has copied the details from here to #289
