### ISSUE TITLE
Fix timeout/performance problems with "/feeds/all"

### ISSUE THREAD

**Issue by charl3sj** [PARINetwork/pari#384]
At present, hitting /feeds/all on prod times-out. Check if the larger db size and queries are the problem and can be optimised.

Related to https://sentry.io/countermedia/pari/issues/865832229/events/44661334547/

**Comment by gounder** [comment]
Is this the reason why we are getting a 502 error for the following urls:
https://ruralindiaonline.org/feeds/all?format=atom
https://ruralindiaonline.org/feeds/all/
