### ISSUE TITLE
Website Pagination

### ISSUE THREAD

**Issue by gounder** [PARINetwork/pari#391]
Earlier the site had fixed pagination in spite of the author having a lower number of pages for e.g. P Sainath has 9 pages of articles but the site showed pages 10 & 11 as well and these have been crawled by Google Search

The following are some of the author pages for which Google has started showing an error: 
https://ruralindiaonline.org/authors/shalini-singh/?page=2 
https://ruralindiaonline.org/authors/urvashi-sarkar/?page=2 
https://ruralindiaonline.org/authors/sasikumar-vasudevan/?page=2 
https://ruralindiaonline.org/authors/p-sainath/?page=11

Can we have a check where if that author has a lesser page then it will redirect back to the author’s main page For e.g. if visited https://ruralindiaonline.org/authors/p-sainath/?page=11 instead of giving a 404 error it redirected to https://ruralindiaonline.org/authors/p-sainath/

Also, there shouldn’t be a page 1 like this - https://ruralindiaonline.org/authors/sasikumar-vasudevan/?page=1 & https://ruralindiaonline.org/stories/categories/things-we-do?page=1

**Comment by charl3sj** [comment]
> Can we have a check where if that author has a lesser page then it will redirect back to the author’s main page For e.g. if visited https://ruralindiaonline.org/authors/p-sainath/?page=11 instead of giving a 404 error it redirected to https://ruralindiaonline.org/authors/p-sainath/

@gounder Should it go to first page or last page of paginated results? (Pagination won't show if only 1 page from hereon) Thoughts?

**Comment by gounder** [comment]
So the first page will now be https://ruralindiaonline.org/authors/p-sainath/ and not https://ruralindiaonline.org/authors/p-sainath/?page=1. So if someone visits a non-existent page like https://ruralindiaonline.org/authors/p-sainath/?page=11  the should redirect to the first page i.e. https://ruralindiaonline.org/authors/p-sainath/

**Comment by charl3sj** [comment]
- No ?page=1 in pagination bar
- Hitting an out of range page should "redirect" to root page (without 'page' querystring)
