### ISSUE TITLE
Add canonical URL tags

### ISSUE THREAD

**Issue by charl3sj** [PARINetwork/pari#394]
The same page can have multiple urls, because of anchors (#), Variables that don’t change page content (utm_source) www or without www and so on. These page may all get crawled and Google may either show a wrong version of the link or not show any of the version or show multiple versions of the url in search (Thus making both compete with each other to rank higher).

### 1. To Homepage
Add following tag `<link rel="canonical" href="https://ruralindiaonline.org/" />`

### 2. Pagination
The purpose of these tags is to help search engines better understand your paginated series of pages. The proper way to implement rel=prev/next tags is like this:

- One tag on the root page, pointing to the next page in series
`<link rel=”next” href=” https://www.domain.com/category?page=2″/>`
- Two tags on page 2
`<link rel=”prev” href=” https://www.domain.com/category”/>`
`<link rel=”next” href=” https://www.domain.com/category?page=3″/>
`
- Two tags on page 3
`<link rel=”prev” href=” https://www.domain.com/category?page=2″/>
`
`<link rel=”next” href=” https://www.domain.com/category?page=4″/>`
- Repeat the process of implementing a rel=”prev” pointing to the prior page in the sequence and rel=”next” pointing to the next page in the sequence until the second-to-last page.
- One tag on the last page in your paginated series
`<link rel=”prev” href=” https://www.domain.com/category?page=N”/>`, where you replace the “N” with the page number for the second-to-last page in the sequence.

**Comment by gounder** [comment]
Additionally, we should rel canonical tag on all pages, articles, resources, face and their categories.

**Comment by charl3sj** [comment]
- Canonical urls on each page should have the appropriate URL for that page
- Use absolute URLs in the pagination link rels.
