### ISSUE TITLE
Resource page - Sending a resource a mail is not working

### ISSUE THREAD

**Issue by ChitraSatish** [PARINetwork/pari#4]
1. Click the more link under the rural bytes. The resources are displayed in a tiled fashion.
2. Click on any resource. The resource details are opened.  At the bottom of the opened resource page in the left side pane, we have forward button. Click on that
3. We get a form to fill in with the face book, twitter, linked in and google plus buttons. In the same form, we have the email text box. Enter a valid email id.
4. we get the from text box and add a message text box. A button send is also displayed.
5. Enter info in the from
6. Enter a message. After entering 5 characters the form vanishes and we are back to the resource. We are unable to send the resources information through a mail. It happened in the Safari of iPad and also from a desktop.

**Comment by theju** [comment]
This is a part of the slideshare viewer. Not sure we can do anything on this.
