### ISSUE TITLE
Change "Contribute" url to redirect to Google Forms' page

### ISSUE THREAD

**Issue by charl3sj** [PARINetwork/pari#403]
Redirect to https://docs.google.com/forms/d/e/1FAIpQLScfpZfiT28pInGrwKxiIkVrztNMzATkOHmgEXfJwcgkT8nLkg/viewform

**Comment by gounder** [comment]
We didn't want a redirect of the entire page to the Google form, the page had a link to an old Google form, we wanted that updated

**Comment by siddadel** [comment]
This is a very serious and high priority issue. An entire page can not be
reached because of this. A showstopper.

**Comment by charl3sj** [comment]
> We didn't want a redirect of the entire page to the Google form, the page had a link to an old Google form, we wanted that updated


And how do you propose I decipher that that's what you wanted from this email?
<img width="400" alt="Screen Shot 2019-09-08 at 1 25 42 PM" src="https://user-images.githubusercontent.com/1017170/64586266-72350a80-d3b9-11e9-98fa-34211943cf45.png">

Also, please ruminate on why these issues have to hit prod before they are noticed and never brought up during the entirety of the duration this card was open and changes deployed to staging/UAT. This is happening very frequently now.
