### ISSUE TITLE
All articles page showing draft articles

### ISSUE THREAD

**Issue by gounder** [PARINetwork/pari#405]
all articles page is listing articles which are in draft status.
https://ruralindiaonline.org/articles/ 

We have many articles by P. Sainath which in draft status, many of these will have the featured image of another article showing in the listing as well.

**Comment by siddadel** [comment]
This is perhaps not fixed. Articles such as these are showing.

https://ruralindiaonline.org/articles/vidharbha:-awaiting-a-deadly-harvest

**Comment by siddadel** [comment]
I don't think this issue is closed. Unpublished articles that are in draft
status are still being shown.

For instance no articles of this author are being shown because all
articles by this author are scrapped draft articles.
https://ruralindiaonline.org/authors/sainath

But they show in articles/

**Comment by charl3sj** [comment]
That's because you're logged into Wagtail/django-admin. Try in an Incognito window.
