### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by gounder** [PARINetwork/pari#407]
We are unable to upload images on wagtail, clicking the Choose an image button doesn't do anything anymore.

We had this issue while uploading faces but the issue is present across the for image upload buttons.

This is critical, please check.

**Comment by charl3sj** [comment]
> We are unable to upload images on wagtail, clicking the Choose an image button doesn't do anything anymore.

Steps to reproduce?  I just tried it out and it worked fine...

**Comment by gounder** [comment]
Issue was resolved by @siddadel
