### ISSUE TITLE
[UI] About PARI - The Story of PARI page

### ISSUE THREAD

**Issue by gayathrim** [PARINetwork/pari#42]
**In Scope:**
- Static Page design like in mockup
- Categories are restricted to only a few like in mockup (Original writeup has many)
- Links to sections appropriately.

**Defects**
- <del> 4th para has links in the mockup, which is missing.
- <del> 1st para after This is where PARI comes in has links in mockups, which is missing.
- <del> 'What's on PARI', 'This is where PARI comes in' should be bold like in mockup & word.
- <del> More line space needed after the grey line splitter in the Categories section.
- <del> Line spacing on the RHS for the quotes is more. Should be less.
- <del> There should be more space between the Quotes and the quoter name in the RHS
- <del> Quoter names in the RHS doesn't look like the same red color as "About PARI" highlight is.
- <del> Feels like there is a subtle gap between the PARI Logo and the text content below. Everything should start in the same imaginary left line.
- <del> Can be more space between grey line and consider donating to PARI heading in the RHS
- <del> Text size under Donate money & contribute to PARI is smaller. Mockup has the same text size as the rest but lesser line spacing than the other text on the LHS. - Take RHS line spacing from [here](http://54.255.193.26/pages/donate/)
- <del> More line spacing between RHS headings and the text below.
- <del> There can be more space after Neville Roy Singham & the grey splitter line
- <del> "We're also trying to create subtitling.." this sentence should have space before. Right now, no space between full stop and this sentence.
- <del> things we do has two paragraphs. Currently all are put in one para.
- <del> Under Donate Money in RHS, "CounterMedia Trust" should be in bold as in word doc.

**Comment by sankarpatw** [comment]
@gayathrim 
    I had fixed your comments.  Please check and let me know if there any more changes.
