### ISSUE TITLE
[UI] Individual Photo Album

### ISSUE THREAD

**Issue by gayathrim** [PARINetwork/pari#61]
Effort: M

**In Scope:**
- Responsive design as shown in mockup.
- On clicking the photo albums from photo albums home, the photo viewer should open full screen with the cover image and album title, description, photographer, location, share icons on top of the image.

The photo viewer needs to have 
- pause & play functionality to start & stop slideshow.
- Back button which takes user to photo albums home page
- i icon to display info about the photo on the right side panel which slides in as shown in mockup 
- Image description should come on the top if any or left blank. Title, Photographer, Date, location at the bottom on the side panel.
- The i icon changes to back icon once the panel opens. On clicking again, it slides back.
- New browser tab full screen image icon placed before i icon.
- Previous & Next button styling on photos & on top panel where we also show the count of images in album
- Last slide should be author bio slide. (styling is out of scope)

**Out of Scope:**
- Grid View
- Volume control
- Author bio styling
- You may also like functionality not present currently for talking albums & albums in prod

Tasks
Move functionality from album detail to album list - done
Load album specific slides - done
Slideshow play, pause - done
Author styling - wip
On click of album, prevent default click to link
Fix top menu styling including mobile - wip
Mobile menu should have title, and dots style-wip
Overall style fix for the side description bar-wip
Fix models with proper methods

**Defects:**

**Priority 1:**
- <del>Title cover not done.-done 👍 
- <del> Remove italics for description. 👍 
- <del>Slide change time can be increased to 5 secs 👍 
- <del>In Mobile, the bottom half with description, author etc is not scrollable. hence some information is hidden. - The fix is not appropriate. Though the description is scrollable, it is not readable. The entire bottom section can be made scrollable together.
- <del> In Mobile, when i icon is clicked, the entire bottom section till end of screen should be in grey. Now the grey appears only for a fixed width. 👍 
- <del> Description on title card is getting hidden- done
- <del> After coming back from grid, the play icon is shown even though slideshow is still playing. Should be pause button.- done

**Priority 2:**
- <del> Alignment of menu icons
- <del> Centre alignment of images.
- <del>On clicking the photo album link/ image it goes to old slide page. Slideshow popup should open wherever the user clicks in the photo album box.-done 👍 
- <del> Once the slideshow starts after clicking the album, there should be pause button on the menu. Currently we have play button.-done
- Space between date & year comma .. implementation issue
- <del>Thinner left & right main navigation arrows to be placed. Very thick right now. 👍 
- <del> All menu icons to be in same size. -  done
- <del> Author information comes in last slide description like in Small farmer big heart album. And last image slide description comes additional to author info on the author slide. - Data issue. - Corrected in Prod

**Comment by siddadel** [comment]
@kushboojain We will have to overrule that and add the italics style. The editors at PARI need the italics to appear.
