### ISSUE TITLE
Broken link in the page PARI publishing Guidelines

### ISSUE THREAD

**Issue by ChitraSatish** [PARINetwork/pari#7]
1. From home page -> click the link contact us
2. In the pick list select - "How do I contribute content"
3. Click on the guidelines hyperlink from the text shown below the pick list
4. PARI publishing guidelines page will be opened.
5. Go to the seventh point under "Some simple rules about producing output for PARI"
6. Click on the link Kynja Bhabha

I got the page not found error. This needs to be fixed.

**Comment by theju** [comment]
Fixed. Please verify and close.

**Comment by ChitraSatish** [comment]
Verified. The issue is fixed.

**Comment by ChitraSatish** [comment]
Issue has been  verified and closed

On Mon, Sep 28, 2015 at 7:46 PM, Thejaswi Puthraya <notifications@github.com
