### ISSUE TITLE
[Bug] Language for each page toggles to 'Urdu' sometimes automatically

### ISSUE THREAD

**Issue by gayathrim** [PARINetwork/pari#80]
Sometimes the page alignment gets automatically changed to Urdu without user selecting the language.

**Dev tasks**
- Recreate the issue by using different approaches. Mostly related to login
- Try Thejaswi's solution.

**Comment by siddadel** [comment]
I have postd a question on Wagtail's official stackoverflow page. Here:
https://stackoverflow.com/questions/44385265/language-for-each-page-toggles-to-urdu-sometimes-automatically

Please add or suggest changes.
