### ISSUE TITLE
Pre populated values could be cleared in the Contact Us

### ISSUE THREAD

**Issue by ChitraSatish** [PARINetwork/pari#9]
1. From the home page, click on the contact us link.
2. Pick the category Story Pitch / Idea
3. Enter the Name, email, message and click on the send button. You get a message "Your query has successfully been sent"
4. Now select Others from the pick list.
5. The Name, email and message are pre populated. Is it by design we want to retail the previously entered values? Else we can clear the values.

**Comment by theju** [comment]
Now should be cleared after successfully posting it.

**Comment by theju** [comment]
I am closing this now as it seems to have been fixed. Please reopen if that's not the case.
