### ISSUE TITLE
CI/CD Setup for OSS + dev team

### ISSUE THREAD

**Issue by gayathrim** [PARINetwork/pari#98]
**Scope:**
- Evaluate free cloud CI options(free for OSS). Say Travis, CircleCI
- Run al the tests for every commit
- Ability to deploy to staging env on a trigger., say on a branch merge

**Comment by sankarpatw** [comment]
Travis for CI and CD to staging environment is done.

**Comment by sankarpatw** [comment]
https://travis-ci.org/PARINetwork/pari/
